
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F103C8 --probe c0de:cafe:1C2703145216303030303032"

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "info"
